fix prep file so we can patch the test and still run

diff --git a/lang/semgrep-grammars/src/semgrep-julia/prep b/lang/semgrep-grammars/src/semgrep-julia/prep
--- a/lang/semgrep-grammars/src/semgrep-julia/prep
+++ b/lang/semgrep-grammars/src/semgrep-julia/prep
@@ -1,1 +1,46 @@
-../prep.common
+#! /usr/bin/env bash
+#
+# Import and patch up external files.
+#
+# Not the generic script, because we've updated our version of the Julia
+# grammar to return a slightly different syntax tree
+#
+set -eu -o pipefail
+
+name=$(basename "$(pwd)" | sed -e 's/semgrep-//')
+echo $(pwd)
+
+mkdir -p src
+(
+  cd src
+  rm -f scanner.c scanner.cc
+  scanner_c=../../tree-sitter-"$name"/src/scanner.c
+  scanner_cc="$scanner_c"c
+  unicode_h=../../tree-sitter-"$name"/src/unicode.h
+  if [[ -e "$scanner_c" ]]; then
+    ln -sf "$scanner_c" .
+  elif [[ -e "$scanner_cc" ]]; then
+    ln -sf "$scanner_cc" .
+  fi
+)
+
+mkdir -p test/corpus
+(
+  cd test/corpus
+  rm -f inherited
+  # The root of the tests is either 'test/corpus' or 'corpus' as per
+  # tree-sitter documentation.
+  for dir in test/corpus corpus; do
+    corpus=../../../tree-sitter-"$name"/$dir
+    if [[ -e "$corpus" ]]; then
+      # A copy, so we can run `tree-sitter test -u` and not modify the original
+      # in tree-sitter-julia
+      cp -r "$corpus" inherited
+      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+      echo "Your Julia tests may fail due to us changing the syntax tree slightly."
+      echo "If you have a failing test due to 'interpolation_expression' being"
+      echo "parsed as 'identifier', simply patch the test before you commit."
+      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+    fi
+  done
+)
