Add --dry-run option to 'release' script + 'make dry'

diff --git a/lang/release b/lang/release
--- a/lang/release
+++ b/lang/release
@@ -5,38 +5,68 @@
 #
 set -eu -o pipefail
 
+prog_name=$(basename "$0")
+
+usage() {
+  cat <<EOF
+Usage: $prog_name [options]
+Options:
+  --dry-run
+      Do everything except committing the result to the git repo for
+      ocaml-tree-sitter-lang. Also, this mode allows running without a
+      clean git status in ocaml-tree-sitter. This is useful for testing.
+  --help
+      Print this message and exit.
+EOF
+}
+
 error() {
-  echo "Error: $*" >&2
+  echo "Error in '$prog_name': $*" >&2
   exit 1
 }
 
-langs=("$@")
+langs=()
+dry_run=false
+
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    --dry-run)
+      dry_run=true
+      ;;
+    --help)
+      usage
+      exit 0
+      ;;
+    *)
+      langs+=("$1")
+  esac
+  shift
+done
 
 id=$(git rev-parse --short HEAD)
-if [[ -n "$(git status --porcelain)" ]]; then
-  cat 2>&1 <<EOF
+
+if [[ "$dry_run" = false ]]; then
+  if [[ -n "$(git status --porcelain)" ]]; then
+    cat 2>&1 <<EOF
 git status is not clean.
-Please add and commit files until 'git status' shows a clean status,
-then retry.
+Possible resolutions:
+- pass the --dry-run option to $prog_name.
+- add and commit files until 'git status' shows a clean status.
 EOF
-  exit 1
+    exit 1
+  fi
 fi
 
-if [[ ! -d ocaml-tree-sitter-lang ]]; then
-  git clone git@github.com:returntocorp/ocaml-tree-sitter-lang.git
-fi
-# Stay on whatever branch is checked out.
-
-repo="ocaml-tree-sitter-lang"
+opt_run() {
+  if [[ "$dry_run" = true ]]; then
+    echo "[dry run] $*"
+  else
+    echo "[run] $*"
+    "$@"
+  fi
+}
 
 # Copy interesting files, such as the original grammar or the license.
-#
-# Assumptions:
-# - current folder is the language's destination folder.
-# - the files to copy are found in file 'fyi.list' and must exist.
-# - the destination for these files is 'fyi/'.
-# - the source path for these files is relative to ocaml-tree-sitter's
-#   'lang' folder.
 #
 # e.g.:
 #   $ cat lang/go/fyi.list
@@ -45,20 +75,27 @@ repo="ocaml-tree-sitter-lang"
 #   semgrep-grammars/src/semgrep-go/grammar.js
 #
 copy_fyi_files() {
-  if [[ -e fyi.list ]]; then
-    paths=$(cat fyi.list | grep -v '^ *#' | grep -v '^ *$')
+  if [[ -e "$fyi_list" ]]; then
+    paths=$(cat "$fyi_list" | grep -v '^ *#' | grep -v '^ *$')
     for path in $paths; do
-      local src=../$path
-      local dst=fyi/$path
+      mkdir -p "$fyi_dst"
+      local src=$path
+      local dst=$fyi_dst/$path
       if [[ ! -e "$src" ]]; then
         error "[$(pwd)] Missing file specified in fyi.list: $src"
       fi
       mkdir -p $(dirname "$dst")
       cp "$src" "$dst"
-      git add "$dst"
     done
   fi
 }
+
+if [[ ! -d ocaml-tree-sitter-lang ]]; then
+  git clone git@github.com:returntocorp/ocaml-tree-sitter-lang.git
+fi
+# Stay on whatever branch is checked out.
+
+dst_repo="ocaml-tree-sitter-lang"
 
 # Copy the files that we find.
 #
@@ -66,7 +103,7 @@ for lang in "${langs[@]}"; do
   make -C "$lang" clean
   make -C "$lang" gen
   if [[ -d "$lang"/ocaml-src ]]; then
-    dst="$repo"/"$lang"
+    dst="$dst_repo"/"$lang"
     mkdir -p "$dst"
     cp -a "$lang"/ocaml-src/lib "$dst"
     cp -a "$lang"/ocaml-src/bin "$dst"
@@ -83,20 +120,19 @@ for lang in "${langs[@]}"; do
     fi
 
     # new way of copying interesting files
-    (
-      cd "$dst"
-      copy_fyi_files
-    )
+    fyi_list="$lang"/fyi.list
+    fyi_dst="$dst/fyi"
+    copy_fyi_files
   else
     error "Missing folder $lang/ocaml-src"
   fi
 done
 
 (
-  cd "$repo"
+  cd "$dst_repo"
   git add .
   git status
-  git commit -m "Release files generated by ocaml-tree-sitter $id."
+  opt_run git commit -m "Release files generated by ocaml-tree-sitter $id."
   branch=$(git rev-parse --abbrev-ref HEAD)
-  git push origin "$branch"
+  opt_run git push origin "$branch"
 )
