wip: tweak release to allow working with new langs

diff --git a/lang/release b/lang/release
--- a/lang/release
+++ b/lang/release
@@ -20,12 +20,15 @@ for 'typescript' and for 'tsx'. You need to release both:
   ./$prog_name typescript
   ./$prog_name tsx
 
-Usage: $prog_name LANG
+Usage: $prog_name [--dry-run] [--make-new] LANG
 Options:
   --dry-run
       Do everything except committing the result to the git repo
       semgrep-LANG. Also, this mode allows running without a
       clean git status in ocaml-tree-sitter. This is useful for testing.
+  --make-new
+      Make a new local repository in the export dir. Useful when adding
+      support for a new language.
   --help
       Print this message and exit.
 EOF
@@ -38,11 +41,15 @@ error() {
 
 lang=''
 dry_run=false
+make_new=false
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
     --dry-run)
       dry_run=true
+      ;;
+    --make-new)
+      make_new=true
       ;;
     --help)
       usage
@@ -150,17 +157,36 @@ copy_fyi_files() {
 export_dir="export"
 mkdir -p "$export_dir"
 repo="semgrep-$lang"
+remote_url="git@github.com:semgrep/$repo.git"
 
 (
   cd "$export_dir"
   if [[ ! -d "$repo" ]]; then
-    git clone git@github.com:semgrep/"$repo".git
+    echo "[clone] $remote_url"
+    if git clone "$remote_url" "$repo"; then
+      :
+    else
+      if [[ "$make_new" = true ]]; then
+        echo "[init] Creating new local repo $repo."
+        mkdir -p "$repo"
+        cd "$repo"
+        git init
+        git remote add origin "$remote_url" || true
+      else
+        error "Failed to clone $remote_url. Re-run with --new to initialize a local repo."
+      fi
+    fi
   fi
 )
 
-branch=$(git -C "$export_dir/$repo" rev-parse --abbrev-ref HEAD)
-echo "[$export_dir/$repo] Pulling branch '$branch'"
-git -C "$export_dir/$repo" pull origin "$branch" --ff-only
+if [[ "$make_new" != true ]];
+then
+  branch=$(git -C "$export_dir/$repo" rev-parse --abbrev-ref HEAD)
+  echo "[$export_dir/$repo] Pulling branch '$branch'"
+  git -C "$export_dir/$repo" pull origin "$branch" --ff-only
+else
+  branch="main"
+fi
 
 # Copy the files that we find.
 #
@@ -189,6 +215,7 @@ fi
   git status
   if [[ -n "$(git status --porcelain)" ]]; then
     opt_run git commit -m "Release files generated by ocaml-tree-sitter $id."
+    # This may fail if remote doesn't exist yet; that's okay.
     opt_run git push origin "$branch"
   fi
 )
